### ISSUE TITLE
Can't get paired end scRNAseq fastq file.

### ISSUE THREAD

**Issue by uui23** [YeoLab/Yeo_STAMP_Nature_Methods#3]
I am inspired by your research and want to have a look the scRNAseq, but I encounter a problem.
10x v3 library should be paired end library. I also found this page showed it is paired end.
https://www.ebi.ac.uk/ena/browser/view/SRR12391497?show=reads 
But I download the data called SRR12391497.fastq.gz from the database, it only contains 1 fastq file for each sequence experiment.

![image](https://user-images.githubusercontent.com/19822530/132476754-f66ad7a6-250e-4161-91f8-e19b0dece4c9.png)

I have no idea how to split them to reads1 and reads2 that are used as input of cellranger.
I also try use fastq-dump --split to spit the SRR file. But I think the software itself is too weird to get correct results.
So, if there is any way to split them or to get 2 separated fastq files for cellranger to produce gene expression matrix?
Thank you!

**Comment by byee4** [comment]
https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR12391497

I'd recommend starting with the possorted genome bam file, and use Cellranger's bamtofastq (https://support.10xgenomics.com/docs/bamtofastq) to get the fastq files. I'm not sure what SRA does, but it may not be in the appropriate format for Cellranger
